on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER_CARNES }}
        username: ${{ secrets.FTP_USERNAME_CARNES }}
        password: ${{ secrets.FTP_PASSWORD_CARNES }}
        server-dir: /httpdocs/
        protocol: ftps
        port: 21
        exclude: |
          **/plataform/lib/Excel/**
          **/plataform/assets/**
          **/plataform/fckeditor/**
          **/plataform/js/fckeditor/**
          plataform/config.inc.php
